### ISSUE TITLE
Refactor Output Properties to allow more reliable saving

### ISSUE THREAD

**Issue by marcusdroy** [boomerang-io/flow.service.workflow#127]
Instead of saving workflow output properties directly on the running workflow, save them on each individual task execution, then after workflow is completed, save them on the workflow activity, this should allow them to be saved more consistently and support parallelism.

**Comment by tlawrie** [comment]
Hi @marcusdroy were you want to have this attached to a particular release or is it just for the backlog?

**Comment by timrbula** [comment]
@amhudson Also to take a look at this along with other issue
