### ISSUE TITLE
Clean code and handle some NPEs that may occur

### ISSUE THREAD

**Issue by AndreiOla** [boomerang-io/flow.service.workflow#211]
**Is your request related to a problem? Please describe.**
Clean code and handle some NPEs that may occur

**Describe the solution you'd like**
Remove try-catch blocks for 'general' Exceptions. I think those were RuntimeExceptions, because there were unhandled null values.
Remove unnecessary operations.
Remove parameters not used and a 'throws Exception'.

**Describe the benefits or justification for this request**
Cleaner code

**Comment by tlawrie** [comment]
Bumping as advised by @gchickma
