### ISSUE TITLE
Can't open the page Manage->Team Tasks

### ISSUE THREAD

**Issue by Amy0511** [boomerang-io/flow.service.workflow#220]
**Describe the bug**
Got 403 when open Manage->Team Tasks in standalone flow and cicd flow.

**To Reproduce**
https://ocp2.cloud.boomerangplatform.net/dev/flow/apps/flow/manage/task-templates

- Commands to run
- Interactions to cause issue to happen

**Expected behavior**

**Screenshots**
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/87841473/178387042-6ca92989-8386-468d-90c9-0357803765a4.png">

**Environment (please complete the following information):**

- OS: [e.g. MacOS]
- Browser [e.g. chrome, firefox]

**Additional context**

**Comment by tlawrie** [comment]
Hi @Amy0511 do you know if you have any teams. Normally this page would only be available to those that are in teams. Its not available to those with just personal workflows.

Also do you know what version of Flow this relates to?

**Comment by tlawrie** [comment]
Ok. I've verified that this is an issue on the latest version of Flow (3.10.0) but seeing as none of the network calls fail and they all return data, this might be a front end web app issue.

@BenjaminRuby ?

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/16438811/178387714-185daaf8-3158-43f5-91fd-0ddddfa7fc30.png">

**Comment by BenjaminRuby** [comment]
@tlawrie @gchickma this does look like an issue on the UI. From a quick look, it seems that our `ProtectedRoute` is throwing the error. I will take a closer look as to why a bit later

**Comment by gchickma** [comment]
Thx @BenjaminRuby much appreciated.

**Comment by BenjaminRuby** [comment]
The issue is that the UI is looking for `team.tasks` in the feature flags endpoint. It is not showing the Team task manager feature if `team.tasks` is not enabled.

I don't see `team.tasks` returning in the response in our OCP dev instance.

**Comment by BenjaminRuby** [comment]
`{activity: true
enable.verified.tasks.edit: true
global.parameters: true
insights: true
team.management: true
team.parameters: true
user.management: true
workflow.quotas: true
workflow.tokens: true
workflow.triggers: true}`

^is what I am seeing being returned by the /features endpoint

**Comment by Amy0511** [comment]
@BenjaminRuby Many thanks for your help to find the root cause.
@shenqinb-star As I have no write access to this repo, could you please help to fix the API by updating the "`getFlowFeatures()`" in class "`FeatureServiceImpl`" and adding "`features.put("team.tasks",settingsService.getConfiguration("features", "teamTasks").getBooleanValue());`"
@gchickma Is it possible to add me "mingxias@cn.ibm.com" to this repo?

**Comment by tlawrie** [comment]
Hi @Amy0511 the contribution method unless a maintainer is based on Open Source methods. You would fork the repo, and then submit a PR from your fork.

**Comment by Amy0511** [comment]
@tlawrie Thank you and created a PR for it.

**Comment by Amy0511** [comment]
Verified and close it.
